### PR TITLE
Allow for dynamic config key

### PR DESCRIPTION
**Pull request by Mazyod**
I borrowed the practice seen here:
https://github.com/uber/node-dot-arcanist/blob/master/.arcanist/tap/tap/TAPTestEngine.php

Now, the config is loaded much simpler, and supports arcanist extensions multi engine. Are you interested in merging this? If so, I can clean it up, update the docs, ... etc.

```js
{
  "phabricator.uri" : "...",
  "load": [
    ".devtools/swift-linter",
    ".devtools/arc-xcode-test-engine-develop",
    ".devtools/arcanist-extensions-master/multi_test_engine"
  ],
  "unit.engine": "MultiTestEngine",
  "unit.engine.multi-test.engines": [
    {
      "engine": "XcodeUnitTestEngine",
      "unit.engine.xcode.config": {
        "build": {
          "workspace": "XYZ.xcworkspace",
          "scheme": "RunUnitTests",
          "configuration": "Debug",
          "destination": "platform=iOS Simulator,name=iPhone SE"
        }
      }
    },
    {
      "engine": "XcodeUnitTestEngine",
      "unit.engine.xcode.config": {
        "build": {
          "workspace": "XYZ.xcworkspace",
          "scheme": "ToolsCheckTests",
          "configuration": "Debug"
        }
      }
    }
  ]
}
```

### CODE REVIEW

**Comment by Mazyod** [comment]
I signed it!

**Comment by jverkoey** [comment]
Nice! Will this be a breaking change for existing clients? Either way, let's aim to merge this in.

**Comment by Mazyod** [comment]
I think I can make it a non-breaking change, support both configuration for the time being.

I'll work on this PR this week then!

**Comment by Mazyod** [comment]
@hossamghareeb will take this in another PR, and hopefully contribute a few other fixes! Thanks @jverkoey!

**Pull request closed without merging**
